// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXandPY7YKtmW8gf8rimVqpCosuIE153Y',
    appId: '1:789469943477:web:6ef3ab3dcee88d7d4990fc',
    messagingSenderId: '789469943477',
    projectId: 'yalla-shoghl-ba1e0',
    authDomain: 'yalla-shoghl-ba1e0.firebaseapp.com',
    storageBucket: 'yalla-shoghl-ba1e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI4MY_-v1HuMhBs5HMsqn58MSYOxT6dQ8',
    appId: '1:789469943477:android:2d3aef2d17d979be4990fc',
    messagingSenderId: '789469943477',
    projectId: 'yalla-shoghl-ba1e0',
    storageBucket: 'yalla-shoghl-ba1e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaj1JvOitk4dCsLIRg83zYVZj87S8vSLI',
    appId: '1:789469943477:ios:3745a9fc23fbcb884990fc',
    messagingSenderId: '789469943477',
    projectId: 'yalla-shoghl-ba1e0',
    storageBucket: 'yalla-shoghl-ba1e0.firebasestorage.app',
    androidClientId:
        '789469943477-3kj3jcdbuqfui1edjlhg1ksgd66clcbg.apps.googleusercontent.com',
    iosClientId:
        '789469943477-dllg8s6ao0vfnandvp52b07ue7i5c6me.apps.googleusercontent.com',
    iosBundleId: 'com.example.yallaShoglAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXandPY7YKtmW8gf8rimVqpCosuIE153Y',
    appId: '1:789469943477:web:c627a18e9770909b4990fc',
    messagingSenderId: '789469943477',
    projectId: 'yalla-shoghl-ba1e0',
    authDomain: 'yalla-shoghl-ba1e0.firebaseapp.com',
    storageBucket: 'yalla-shoghl-ba1e0.firebasestorage.app',
  );
}
